# Generated by Django 5.2.3 on 2025-11-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(help_text='Introduction text for the About Us section')),
                ('team_photo', models.ImageField(blank=True, help_text='Common team photo', null=True, upload_to='about_us/')),
                ('team_member_1_name', models.CharField(blank=True, help_text='Name of team member 1', max_length=255, null=True)),
                ('team_member_1_designation', models.CharField(blank=True, help_text='Designation of team member 1', max_length=255, null=True)),
                ('team_member_1_description', models.TextField(blank=True, help_text='Description of team member 1', null=True)),
                ('team_member_1_photo', models.ImageField(blank=True, help_text='Photo of team member 1', null=True, upload_to='about_us/team/')),
                ('team_member_2_name', models.CharField(blank=True, help_text='Name of team member 2', max_length=255, null=True)),
                ('team_member_2_designation', models.CharField(blank=True, help_text='Designation of team member 2', max_length=255, null=True)),
                ('team_member_2_description', models.TextField(blank=True, help_text='Description of team member 2', null=True)),
                ('team_member_2_photo', models.ImageField(blank=True, help_text='Photo of team member 2', null=True, upload_to='about_us/team/')),
                ('team_description', models.TextField(blank=True, help_text='Description of the team', null=True)),
                ('introduction_video', models.URLField(blank=True, help_text='URL of the introductory video', null=True)),
                ('mission_statement', models.TextField(help_text='Company mission statement')),
                ('vision_statement', models.TextField(help_text='Company vision statement')),
                ('achievement_title_1', models.CharField(blank=True, help_text='Title of achievement 1', max_length=255, null=True)),
                ('achievement_description_1', models.TextField(blank=True, help_text='Description of achievement 1', null=True)),
                ('achievement_photo_1', models.ImageField(blank=True, help_text='Photo for achievement 1', null=True, upload_to='about_us/achievements/')),
                ('achievement_title_2', models.CharField(blank=True, help_text='Title of achievement 2', max_length=255, null=True)),
                ('achievement_description_2', models.TextField(blank=True, help_text='Description of achievement 2', null=True)),
                ('achievement_photo_2', models.ImageField(blank=True, help_text='Photo for achievement 2', null=True, upload_to='about_us/achievements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('static_icon', models.ImageField(blank=True, null=True, upload_to='static_services/')),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_service_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('projects', models.PositiveIntegerField(default=0)),
                ('hours_of_support', models.PositiveIntegerField(default=0)),
                ('hard_workers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='team/')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the client', max_length=255)),
                ('designation', models.CharField(blank=True, help_text="Client's designation (e.g., CEO, Designer)", max_length=255, null=True)),
                ('text', models.TextField(help_text='Testimonial content')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the client', null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_testimonial_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['order'],
            },
        ),
    ]
