# Generated by Django 5.2.3 on 2025-11-14 22:39

import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOurWorkBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_our_work_brochure', models.FileField(blank=True, help_text='Upload a PDF brochure to let users check your work', null=True, upload_to='check_our_work/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the brochure was uploaded')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this brochure is currently active/visible')),
            ],
            options={
                'verbose_name': 'Check Our Work Brochure',
                'verbose_name_plural': 'Check Our Work Brochures',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feature amenity (e.g., Swimming Pool, Gym)', max_length=100)),
            ],
            options={
                'verbose_name': 'Feature Amenity',
                'verbose_name_plural': 'Feature Amenities',
            },
        ),
        migrations.CreateModel(
            name='NearbyPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the nearby amenity (e.g., Hospital, School, Metro)', max_length=100)),
                ('distance_value', models.DecimalField(decimal_places=2, help_text='Distance value', max_digits=8)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('m', 'Meters')], default='km', help_text='Distance unit', max_length=2)),
            ],
            options={
                'verbose_name': 'Nearby Place',
                'verbose_name_plural': 'Nearby Places',
            },
        ),
        migrations.CreateModel(
            name='PropertyCalculatorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, verbose_name='Property Category')),
                ('property_type', models.CharField(max_length=20, verbose_name='Property Type')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor Number')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('flat_society_name', models.CharField(max_length=255, verbose_name='Flat/Society Name')),
                ('area', models.PositiveIntegerField(verbose_name='Area (in sq ft)')),
                ('property_life', models.PositiveIntegerField(verbose_name='Property Life (in years)')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('photo', models.ImageField(upload_to='property_inquiries/%Y/%m/%d/', verbose_name='Property Photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='property_inquiries/%Y/%m/%d/', verbose_name='Property Video')),
                ('document', models.FileField(blank=True, null=True, upload_to='property_inquiries/%Y/%m/%d/', verbose_name='Additional Document')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Calculator Inquiry',
                'verbose_name_plural': 'Property Calculator Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Property Location',
                'verbose_name_plural': 'Property Locations',
            },
        ),
        migrations.CreateModel(
            name='InteriorDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the customer', max_length=100, verbose_name='Customer Name')),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('property_types', models.CharField(choices=[('flat', 'Flat'), ('bungalow', 'Bungalow'), ('penthouse', 'Penthouse')], help_text='Select property type', max_length=20, verbose_name='Property Type')),
                ('sqft', models.PositiveIntegerField(blank=True, help_text='Property area in square feet', null=True, verbose_name='Square Feet (SBA)')),
                ('service_types', models.CharField(choices=[('turnkey', 'Turn key'), ('consultancy', 'Consultancy service')], help_text='Select service type', max_length=20, verbose_name='Service Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Interior Design Request',
                'verbose_name_plural': 'Interior Design Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='services_in_created_3cb1b4_idx'), models.Index(fields=['phone_number'], name='services_in_phone_n_ea66e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuyProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('resale', 'Resale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('all', 'ALL'), ('leasing', 'LEASING'), ('investment', 'INVESTMENT'), ('resale_residential', 'RESALE RESIDENTIAL')], default='all', max_length=20)),
                ('configuration', models.CharField(blank=True, choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk', '4BHK'), ('5bhk', '5BHK'), ('duplex', 'Duplex'), ('tenament', 'Tenament'), ('Bungalow', 'Bungalow'), ('villa', 'Villa')], max_length=20, null=True)),
                ('commercial_type', models.CharField(blank=True, choices=[('showroom', 'Showroom'), ('office', 'Office'), ('shop', 'Shop'), ('corporate_floors', 'Corporate Floors')], max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('rent_per_sqft', models.PositiveIntegerField(blank=True, help_text='On SBA', null=True)),
                ('lockin_period', models.CharField(blank=True, max_length=200, null=True)),
                ('increment', models.CharField(blank=True, help_text='In Percentage (%)', max_length=200, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sqft', max_digits=10)),
                ('area_in_sqyards', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square yards', max_digits=10, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in INR', max_digits=12, null=True)),
                ('min_budget_unit', models.CharField(choices=[('lakhs', 'Lakhs'), ('crores', 'Crores')], default='lakhs', help_text='Unit for minimum budget', max_length=10)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_budget_unit', models.CharField(choices=[('lakhs', 'Lakhs'), ('crores', 'Crores')], default='lakhs', help_text='Unit for maximum budget', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('brochure_pdf', models.FileField(blank=True, help_text='Upload a PDF brochure for this property', null=True, upload_to='property_brochures/')),
                ('possession_date', models.DateField(blank=True, help_text='Expected or actual date of possession', null=True)),
                ('number_of_units', models.PositiveIntegerField(blank=True, help_text='Total number of units in the project', null=True)),
                ('number_of_lifts', models.PositiveIntegerField(blank=True, help_text='Number of lifts/elevators in the building', null=True)),
                ('number_of_storey', models.PositiveIntegerField(blank=True, help_text='Number of floors/storeys in the building', null=True)),
                ('salient_features', models.TextField(blank=True, help_text='Key features of the property (comma-separated)', null=True)),
                ('is_property_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('feature_amenities', models.ManyToManyField(blank=True, help_text='Features like swimming pool, gym, clubhouse, etc.', related_name='properties', to='services.featureamenity')),
                ('nearby_amenities', models.ManyToManyField(blank=True, help_text='Nearby amenities such as schools, hospitals, etc.', related_name='properties', to='services.nearbyplaces')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.propertylocation')),
            ],
            options={
                'verbose_name': 'Buy Property',
                'verbose_name_plural': 'Buy Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.buyproperties')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='services.buyproperties')),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='property_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.buyproperties')),
            ],
        ),
        migrations.CreateModel(
            name='SellCommercialProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project or building', max_length=100)),
                ('commercial_type', models.CharField(blank=True, choices=[('showroom', 'Showroom'), ('office', 'Office'), ('shop', 'Shop'), ('corporate_floors', 'Corporate Floors'), ('other', 'Other')], max_length=20, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('resale', 'Resale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sqft', max_digits=10)),
                ('area_in_sqyards', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square yards', max_digits=10, null=True)),
                ('budget', models.PositiveIntegerField(help_text='Budget in INR')),
                ('floor_num', models.PositiveIntegerField(blank=True, help_text='Floor number of the commercial property', null=True)),
                ('unit_num', models.CharField(blank=True, help_text='Unit number or identifier (e.g., A-101, B-205)', max_length=20, null=True)),
                ('property_subtype', models.CharField(blank=True, help_text="Please specify the property type (required when 'Other' is selected)", max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sell_commercial_properties/')),
                ('video', models.FileField(blank=True, help_text='Property video (max 50MB, formats: mp4, avi, mov, wmv, mkv, flv, webm)', null=True, upload_to='sell_commercial_properties/videos/', validators=[services.models.validate_video_file])),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_details', models.TextField(blank=True, help_text="Please mention any additional details related to rent, lease, lease increment, or specific requirements you'd like us to know", null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.propertylocation')),
            ],
            options={
                'verbose_name': 'Sell Commercial Property',
                'verbose_name_plural': 'Sell Commercial Properties',
            },
        ),
        migrations.CreateModel(
            name='SellResidentialProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project or building', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('resale', 'Resale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('all', 'ALL'), ('leasing', 'LEASING'), ('investment', 'INVESTMENT'), ('resale_residential', 'RESALE RESIDENTIAL')], default='all', max_length=20)),
                ('configuration', models.CharField(blank=True, choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk', '4BHK'), ('5bhk', '5BHK'), ('duplex', 'Duplex'), ('tenament', 'Tenament'), ('Bungalow', 'Bungalow'), ('villa', 'Villa'), ('other', 'Other')], max_length=20, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sqft', max_digits=10)),
                ('area_in_sqyards', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square yards', max_digits=10, null=True)),
                ('budget', models.PositiveIntegerField(help_text='Budget in INR')),
                ('floor_num', models.PositiveIntegerField(blank=True, help_text='Floor number of the commercial property', null=True)),
                ('unit_num', models.CharField(blank=True, help_text='Unit number or identifier (e.g., A-101, B-205)', max_length=20, null=True)),
                ('property_subtype', models.CharField(blank=True, help_text="Please specify the property type (required when 'Other' is selected)", max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sell_residential_properties/')),
                ('video', models.FileField(blank=True, help_text='Property video (max 50MB, formats: mp4, avi, mov, wmv, mkv, flv, webm)', null=True, upload_to='sell_residential_properties/videos/', validators=[services.models.validate_video_file])),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_details', models.TextField(blank=True, help_text="Please mention any additional details related to rent, lease, lease increment, or specific requirements you'd like us to know", null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.propertylocation')),
            ],
            options={
                'verbose_name': 'Sell Residential Property',
                'verbose_name_plural': 'Sell Residential Properties',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.buyproperties')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorites',
            },
        ),
    ]
